### ISSUE TITLE
Issue/Bug with rdf spdx file generation

### ISSUE THREAD

**Issue by ekongobie** [ekongobie/spdx_id_doc_gen#1]
@udaykor @kestewart @mhc61648 

When I try to generate the rdf document using the line of code below;
https://github.com/ekongobie/spdx_id_doc_gen/blob/ab18c9bfb104dc20d4051abeb11e92ce056d5b01/doc_gen/core.py#L193

I have the following errors:
`
Traceback (most recent call last):
  File "/home/superman/Desktop/spdx_id_env/bin/spdxgen", line 9, in <module>
    load_entry_point('doc-gen', 'console_scripts', 'spdxgen')()
  File "/home/superman/Desktop/spdx_id_env/spdx_id_doc_gen/doc_gen/main.py", line 42, in entry_point
    raise SystemExit(main(args.project_path, args.doc_type))
  File "/home/superman/Desktop/spdx_id_env/spdx_id_doc_gen/doc_gen/main.py", line 33, in main
    spdx_file.create()
  File "/home/superman/Desktop/spdx_id_env/spdx_id_doc_gen/doc_gen/core.py", line 197, in create
    self.output_file.write(result)
TypeError: a bytes-like object is required, not 'str'
`

Then when I remove the `str`; as below;
`write_document(self.spdx_document, spdx_output, validate=False)`

I have this error:
`
Traceback (most recent call last):
  File "/home/superman/Desktop/spdx_id_env/bin/spdxgen", line 9, in <module>
    load_entry_point('doc-gen', 'console_scripts', 'spdxgen')()
  File "/home/superman/Desktop/spdx_id_env/spdx_id_doc_gen/doc_gen/main.py", line 42, in entry_point
    raise SystemExit(main(args.project_path, args.doc_type))
  File "/home/superman/Desktop/spdx_id_env/spdx_id_doc_gen/doc_gen/main.py", line 33, in main
    spdx_file.create()
  File "/home/superman/Desktop/spdx_id_env/spdx_id_doc_gen/doc_gen/core.py", line 193, in create
    write_document(self.spdx_document, spdx_output, validate=False)
  File "/home/superman/Desktop/spdx_id_env/src/spdx-tools/spdx/writers/rdf.py", line 727, in write_document
    writer.write()
  File "/home/superman/Desktop/spdx_id_env/src/spdx-tools/spdx/writers/rdf.py", line 708, in write
    self.graph.serialize(self.out, 'pretty-xml', encoding='utf-8')
  File "/home/superman/Desktop/spdx_id_env/lib/python3.6/site-packages/rdflib/graph.py", line 947, in serialize
    serializer.serialize(stream, base=base, encoding=encoding, **args)
  File "/home/superman/Desktop/spdx_id_env/lib/python3.6/site-packages/rdflib/plugins/serializers/rdfxml.py", line 168, in serialize
    self.writer = writer = XMLWriter(stream, nm, encoding)
  File "/home/superman/Desktop/spdx_id_env/lib/python3.6/site-packages/rdflib/plugins/serializers/xmlwriter.py", line 19, in __init__
    stream.write('<?xml version="1.0" encoding="%s"?>' % encoding)
  File "/usr/lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: string argument expected, got 'bytes'
`

**Comment by udaykor** [comment]
Dear @ekongobie, 

I need your help in replicating the error. Before doing that, We need to do some clean-up. 

Can you commit the SPDX python dependency? `spdx==2.5.0` or the `version` you have used. We do not need this line in the requirements.txt file.
`-e git+https://github.com/spdx/tools-python.git@276e30d5ddeae98e4cefb455b4d245506e6345b1#egg=spdx-tools`

I am at the moment cleaning up to get started locally

**Comment by udaykor** [comment]
@ekongobie can you replace `spdx_output = io.StringIO()` with `spdx_output = io.BytesIO()` and try again?
Also, I need your help to setup a reproducible environment for us. Maybe if you walk me through once, I will help you setup a Dockerfile for faster reproducibility.

**Comment by ekongobie** [comment]
@udaykor In the early stages of the development of this tool, I was using the "pip" version of spdx tools, but then I noticed that it did not have all the functionalities which the "development/github" version has. That is the reason why I thought it better to switch.

[This README link](https://github.com/ekongobie/spdx_id_doc_gen/blob/master/README.md) can help you setup the environment .

The error can be reproduced by trying to generate the rdf spdx file generation.
For instance:
`spdxgen ~/Desktop/test-proj/modules rdf`

**Comment by ekongobie** [comment]
@udaykor Thanks for the correction, I changed `spdx_output = io.StringIO()` to `spdx_output = io.BytesIO()` and the rdf file generation works like charm!

Thanks :)

**Comment by ekongobie** [comment]
resolved
